### ISSUE TITLE
EPIC: OCM Website Enhancement Umbrella

### ISSUE THREAD

**Issue by n-boshnakov** [open-component-model/ocm-website#268]
**What would you like to be added**:
This issue will track work done on the [OCM website](https://ocm.software/) as part of efforts to improve the content there:
- [x] Overview
  - [X] About the OCM Project - https://github.com/open-component-model/ocm-website/pull/258
    - [X] added visualization - diagram showing the projects
    - [X] shortened the text on the page
    - [X] proofread the content
  - [x] Benefits of OCM - https://github.com/open-component-model/ocm-website/pull/258
     - [X] proofread the content
  - [x] Important Terms 
    - [x] proofread the content https://github.com/open-component-model/ocm-website/pull/280
  - [X] Specification
    - [ ] ~~clarified the different versions used and the differences between them~~ - https://github.com/open-component-model/ocm-website/pull/288
    - [X] proofread the content

- [X] Getting Started
  - [X] Installing the OCM CLI - https://github.com/open-component-model/ocm-website/pull/269
    - [X] proofread the content
    - [X] split single long topic into different topics
  - [X] First Steps with OCM - https://github.com/open-component-model/ocm-website/pull/269
    - [X] proofread the content
    - [X] added links

- [x] Tutorials - https://github.com/open-component-model/ocm-website/pull/284
  - [x] proofread the content
  - [x] cleaned up the content
